'use strict';

const { app, BrowserWindow, Menu, session, shell } = require('electron');
const fs = require('node:fs'); const path = require('node:path');
const APP_URL = 'https://tv.apple.com/'; const PARTITION = 'persist:apple-tv';
const APP_HOSTS = new Set(['apple.com', 'www.apple.com', 'tv.apple.com']); const AUTH_HOSTS = new Set(['accounts.google.com', 'appleid.apple.com', 'login.microsoftonline.com']);
let mainWindow; let statePath;
function allowed(host, hosts) { return [...hosts].some((entry) => host === entry || host.endsWith(`.${entry}`)); }
function trusted(value) { try { const url = new URL(value); return url.protocol === 'https:' && (allowed(url.hostname.toLowerCase(), APP_HOSTS) || allowed(url.hostname.toLowerCase(), AUTH_HOSTS)); } catch { return false; } }
function external(value) { if (value.startsWith('mailto:') || value.startsWith('tel:')) { void shell.openExternal(value); return; } try { const url = new URL(value); if (url.protocol === 'http:' || url.protocol === 'https:') void shell.openExternal(url.toString()); } catch {} }
function readState() { try { const state = JSON.parse(fs.readFileSync(statePath, 'utf8')); if (Number.isInteger(state.width) && Number.isInteger(state.height)) return state; } catch {} return { width: 1400, height: 900 }; }
function saveState() { if (!mainWindow || mainWindow.isDestroyed()) return; fs.mkdirSync(path.dirname(statePath), { recursive: true }); fs.writeFileSync(statePath, JSON.stringify(mainWindow.getNormalBounds())); }
function policies(window) { const contents = window.webContents; contents.setWindowOpenHandler(({ url }) => trusted(url) ? { action: 'allow', overrideBrowserWindowOptions: { width: 1100, height: 800, title: 'Apple TV', webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false, sandbox: true, webSecurity: true, partition: PARTITION } } } : (external(url), { action: 'deny' })); contents.on('did-create-window', policies); for (const event of ['will-navigate', 'will-redirect']) contents.on(event, (eventObject, url) => { if (!trusted(url)) { eventObject.preventDefault(); external(url); } }); contents.on('will-download', (_event, item) => item.setSavePath(path.join(app.getPath('downloads'), item.getFilename()))); }
function createMenu() { Menu.setApplicationMenu(Menu.buildFromTemplate([{ label: 'File', submenu: [{ role: 'close' }, { role: 'quit' }] }, { role: 'editMenu' }, { label: 'View', submenu: [{ role: 'reload' }, { role: 'forceReload' }, { role: 'resetZoom' }, { role: 'zoomIn' }, { role: 'zoomOut' }, { role: 'togglefullscreen' }, { role: 'toggleDevTools', accelerator: 'CommandOrControl+Shift+I' }] }, { role: 'windowMenu' }, { role: 'help', submenu: [{ label: 'Apple TV', click: () => mainWindow?.loadURL(APP_URL) }] }])); }
async function createWindow() { statePath = path.join(app.getPath('userData'), 'window-state.json'); mainWindow = new BrowserWindow({ ...readState(), minWidth: 640, minHeight: 480, title: 'Apple TV', icon: path.join(__dirname, '..', 'resources', 'apple-tv.png'), webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false, sandbox: true, webSecurity: true, partition: PARTITION } }); policies(mainWindow); mainWindow.on('resize', saveState); mainWindow.on('move', saveState); mainWindow.on('closed', () => { mainWindow = null; }); await mainWindow.loadURL(APP_URL); }
if (!app.requestSingleInstanceLock()) app.quit(); else { app.on('second-instance', () => { mainWindow?.restore(); mainWindow?.focus(); }); app.whenReady().then(async () => { const appSession = session.fromPartition(PARTITION); appSession.setUserAgent(app.userAgentFallback.replace(/\sElectron\/[^\s]+/, '')); appSession.setPermissionRequestHandler((_webContents, permission, callback) => callback(permission === 'notifications')); createMenu(); await createWindow(); app.on('activate', () => { if (!BrowserWindow.getAllWindows().length) void createWindow(); }); }); app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); }); app.on('before-quit', saveState); }
