'use strict';
const { app, BrowserWindow, Menu, session, shell } = require('electron');
const { configureSession } = require('./permission-policy');
const fs = require('node:fs');
const path = require('node:path');
const APP_URL = 'https://jupyter.org/'; const PARTITION = 'persist:jupyter'; const APP_ID = 'io.github.example.JupyterDesktop';
const APP_HOSTS = new Set(['jupyter.org', 'www.jupyter.org', 'jupyterhub.readthedocs.io']); const AUTH_HOSTS = new Set(['accounts.google.com','consent.google.com','oauth2.googleapis.com','gstatic.com','googleusercontent.com','appleid.apple.com','login.microsoftonline.com','auth0.com','okta.com']); let mainWindow; let statePath;
function allowed(host, set) { return [...set].some((item) => host === item || host.endsWith(`.${item}`)); }
function trusted(value) { try { const u = new URL(value); return u.protocol === 'https:' && (allowed(u.hostname.toLowerCase(), APP_HOSTS) || allowed(u.hostname.toLowerCase(), AUTH_HOSTS)); } catch { return false; } }
function external(value) { if (value.startsWith('mailto:') || value.startsWith('tel:')) return void shell.openExternal(value); try { const u = new URL(value); if (u.protocol === 'http:' || u.protocol === 'https:') void shell.openExternal(u.toString()); } catch {} }
function state() { try { const s = JSON.parse(fs.readFileSync(statePath, 'utf8')); if (Number.isInteger(s.width) && Number.isInteger(s.height)) return s; } catch {} return { width: 1400, height: 900 }; }
function save() { if (!mainWindow || mainWindow.isDestroyed()) return; fs.mkdirSync(path.dirname(statePath), { recursive: true }); fs.writeFileSync(statePath, JSON.stringify(mainWindow.getNormalBounds())); }
function policies(win) { const c = win.webContents; c.setWindowOpenHandler(({ url }) => trusted(url) ? { action: 'allow', overrideBrowserWindowOptions: { width: 1100, height: 800, title: 'Jupyter Desktop', webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false, sandbox: true, webSecurity: true, partition: PARTITION } } } : (external(url), { action: 'deny' })); c.on('did-create-window', policies); for (const event of ['will-navigate','will-redirect']) c.on(event, (e, url) => { if (!trusted(url)) { e.preventDefault(); external(url); } }); c.on('did-redirect-navigation', () => mainWindow?.focus()); c.on('did-navigate', () => mainWindow?.focus()); c.on('will-download', (_e, item) => item.setSavePath(path.join(app.getPath('downloads'), item.getFilename()))); }
function menu() { Menu.setApplicationMenu(Menu.buildFromTemplate([{ label: 'File', submenu: [{ role: 'close' }, { role: 'quit' }] }, { role: 'editMenu' }, { label: 'View', submenu: [{ role: 'reload' }, { role: 'forceReload' }, { role: 'resetZoom' }, { role: 'zoomIn' }, { role: 'zoomOut' }, { role: 'togglefullscreen' }, { role: 'toggleDevTools', accelerator: 'CommandOrControl+Shift+I' }] }, { role: 'windowMenu' }, { role: 'help', submenu: [{ label: 'Jupyter.org', click: () => mainWindow?.loadURL(APP_URL) }] }])); }
async function create() { statePath = path.join(app.getPath('userData'), 'window-state.json'); mainWindow = new BrowserWindow({ ...state(), minWidth: 640, minHeight: 480, title: 'Jupyter Desktop', icon: path.join(__dirname, '..', 'resources', 'jupyter-desktop.png'), webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false, sandbox: true, webSecurity: true, partition: PARTITION } }); policies(mainWindow); mainWindow.on('resize', save); mainWindow.on('move', save); mainWindow.on('closed', () => { mainWindow = null; }); await mainWindow.loadURL(APP_URL); }
if (!app.requestSingleInstanceLock()) app.quit(); else { app.on('second-instance', () => { mainWindow?.restore(); mainWindow?.focus(); }); app.whenReady().then(async () => { const s = session.fromPartition(PARTITION); s.setUserAgent(app.userAgentFallback.replace(/\sElectron\/[^\s]+/, '')); configureSession(s, APP_HOSTS, AUTH_HOSTS); menu(); await create(); app.on('activate', () => { if (!BrowserWindow.getAllWindows().length) void create(); }); }); app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); }); app.on('before-quit', save); }
